### ISSUE TITLE
ID User Name of DNA file

### ISSUE THREAD

**Issue by paravance** [lassefolkersen/impute-me#1]
It appears that the DNA source file assisgned as part of the user id, is being reflected as 23andme.zip and not the true source, i.e. Ancestry, Myheritage, ECT.

Just an observation, to make the output more user specific so it does not appear like the source DNA may actually belong to someone else.

The DNA I submitted was not from 23andme but another provider, and it made me feel uncomfortable in the analysis when a DNA provider file was attached to my DNA submission from a source that was not the company that provided the DNA for the analysis.

Paravance

**Comment by lassefolkersen** [comment]
I'm sorry you felt uncomfortable. The reason it says 23andme is to distinguish the format from other possible output formats, such as gen-format or vcf-format. 23andme-format is so called because it was introduced by 23andme.

I'll put a rename on a to-do list for a future revision of the code

**Comment by paravance** [comment]
Thank You for you sensitivity to my observation..


Gerald


________________________________
