### ISSUE TITLE
How to use commands of this project

### ISSUE THREAD

**Issue by axhem** [lassefolkersen/impute-me#33]
A little bit confuses to fully understand how this project works, how to set up and how to use it commands. After [shiny-server](https://github.com/lassefolkersen/impute-me/blob/master/server_setup.R#L112)  setup what is next step?

**Comment by lassefolkersen** [comment]
Check the file server_setup.R. It has all details.

Although I suspect maybe, as regular user - it'd be better for you just to go to impute.me and read instructions there. You don't need to setup a server yourself if you just want an analysis done

**Comment by axhem** [comment]
@lassefolkersen Already installed the shiny-server able to run the project locally.  I want to make an analysis of my own genomic data. So there is any possibility to extract my own genomic data and make analysis through this app. The second question is that what if I want to use methods and algorithms through cmd/terminal is there any possibility, if yes how? Thank you!

**Comment by lassefolkersen** [comment]
Yes. There is possibility. But I don't have the resources to support your own configuration efforts. If your goal is to analyze your own personal genome, you can use the already configured solution at www.impute.me.
