### ISSUE TITLE
Security issue and deleting data from the site

### ISSUE THREAD

**Issue by hnykda** [lassefolkersen/impute-me#36]
Hi, if I understand correctly, one can load data and after the processing, these are available for eternity under unsecured link with ID in it (~9 numbers). Is there an option to delete the data, shouldn't they just be deleted automatically after e.g. 45 days and could you please please add some authentication mechanism, at least a simple password?

**Comment by lassefolkersen** [comment]
Please read the terms of service. All genomic data (identifiable) is deleted after 14 days. All remaining derived calculations (non-identifiable) are deleted after 2 years.

**Comment by lassefolkersen** [comment]
sorry didn't mean to hit "close issue", I'm happy to discuss further if you'd like. I think this is the more safe solution, because a password would also require an email. And then suddenly it quickly becomes very identifiable

**Comment by hnykda** [comment]
Ah, sorry, I have missed that, my bad :man_facepalming: . I believe that's totally sufficient then and this can be closed.

Thank you for a quick reply and a great service.
