### ISSUE TITLE
can not find configuration.R

### ISSUE THREAD

**Issue by huanglinren** [lassefolkersen/impute-me#37]
I can not find the script configuration.R in source("/home/ubuntu/misc_files/configuration.R")

**Comment by lassefolkersen** [comment]
You have to define the configuration parameters yourself, because they involve stuff such as setting up email adress for sending results etc. That can't be provided in github. But here's an example. The code will warn you on first wrong if any are wrongly defined or missing.
```
maxImputations <- 1
maxImputationsInQueue <- 200
serverRole <- "Node"
hubAddress <- "SOMEIPADRESS"
email_password <- "SOMEPASSWORD"
email_address <- "SOMEEFROMMAILADRESS"
routinely_delete_this <- c("link","data") 
paypal <- "SOMEPAYPALADRESS"
bulk_node_count <- 4
error_report_mail <- "SOMEERRORADRESS"
seconds_wait_before_start <- 30000
```

**Comment by huanglinren** [comment]
OK, thank you again! you are so nice!
