### ISSUE TITLE
Where to find SNPs used in calculation of PRS in AllDiseases?

### ISSUE THREAD

**Issue by liezl200** [lassefolkersen/impute-me#38]
For example, for bipolar disorder:

"Retrieved 819397 SNPs from Hou L et al (PMID 27329760), which were reported to be associated with bipolar disorder. This study reports a total sample size of 34950, as entered on date 2016-06-21. For you, we calculated an all-SNP polygenic risk score of 0.2. You can compare this score with that of other users in above plot. The table below shows the strongest of the SNPs to illustrate the polygenic nature of the trait."

This corresponds to the study from `2019-03-04_trait_overview.xlsx`: 

`bipolar_disorder_27329760	Bipolar disorder	27329760	Hou L`

But when I look at the data from `2019-03-04_semi_curated_version_gwas_central.rdata`, I only see 64k SNPs, and none of them correspond to pmid 27329760.

**Logs:**
`> snps_file<-"2019-03-04_semi_curated_version_gwas_central.rdata"`
`> str(load(snps_file))`
```
[1] "data"
```
`> nrow(gwas_snps)`
```
64377
```
`> data[data$pmid == 27329760]`
```
Error in `[.data.frame`(data, data$pmid == 27329760): undefined columns selected
Traceback:

1. data[data$pmid == 27329760]
2. `[.data.frame`(data, data$pmid == 27329760)
3. stop("undefined columns selected")

```

**Comment by lassefolkersen** [comment]
You're missing a comma. Should be:
 `data[data$pmid == 27329760,]`
Not
 `data[data$pmid == 27329760]`
That'll give you the top-SNPs from Hou et al, the ones shown in the table. The full list is too big to fit in github.

**Comment by liezl200** [comment]
@lassefolkersen wow great catch! It works :)

Is there any way to examine the full list? Where in the paper / supplemental info did you get all those SNPs from? It must be impossible to gather that volume manually!

**Comment by lassefolkersen** [comment]
I intend for these all-SNP scores to eventually go somewhere more official, like [PGS catalog](http://www.pgscatalog.org/). Right now I don't really have the bandwith to also host them officially unfortunately.
