### ISSUE TITLE
Deploying Kandinskyfy module to WeGene?

### ISSUE THREAD

**Issue by xraywu** [lassefolkersen/impute-me#39]
Hi @lassefolkersen my name is Xiaoli and I am an employee of WeGene, a Chinese personal genetic testing company. We allow third party developers to deploy their modules on our platform (free or charged) so users can have more analysis options. I came across Impute-me and found some of your modules very interesting, especially the Kandinskyfy module.

I am wondering if you would like to deploy the module on our platform and refer back to Impute-me? We support R language so migration should be rather straightforward. We will also help during the process.

Cheers,
Xiaoli

**Comment by lassefolkersen** [comment]
Certainly. The code for that module is available in [this folder](https://github.com/lassefolkersen/impute-me/tree/master/kandinsky) and it's freely available under [this licence](https://github.com/lassefolkersen/impute-me/blob/master/LICENSE). If you are interested in that module, you may also be interested in a recent hackaton we did, with the purpose of creating better and more beautiful art based on genetics code. Here's the links to the online presentations of that hackaton: ([link plus extra videos in list](https://www.linkedin.com/posts/activity-6693527913444253696-U1xn)). But feel free to write me, e.g. [wechat](https://bit.ly/33GUXNn), if you want to discuss more :-)
