### ISSUE TITLE
Docker: multithreading support

### ISSUE THREAD

**Issue by ad7718** [lassefolkersen/impute-me#42]
Only one of 8 cores are used when process is running. Is it bug/not impemented or it needs some command line parameters?

**Comment by lassefolkersen** [comment]
The intended behaviour is to multiplex over many samples, i.e. if you upload 8 samples and set the `maxImputations` parameter in `~/misc/configuration.R` to 8 - then the process will use all 8 cores at the same time. There is no multiplexing within one sample.

**Comment by ad7718** [comment]
Thank you for clarification
